// File generated by hand from the Firebase console's per-platform config
// snippets (project: optic-8f64e), in place of running the FlutterFire CLI —
// see the migration guide for why. Web is wired with real values pasted
// from the console; Android/iOS are placeholders until those two apps are
// registered and their config snippets are pasted in too. Attempting to
// run on Android/iOS before that happens will fail at
// `Firebase.initializeApp()` with an authentication error — not a silent
// wrong-project bug — since these placeholder keys don't belong to any
// real Firebase app.
//
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'register a macOS app in the Firebase console and paste its '
          'config here if you need a desktop build.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'register a Windows/desktop-compatible app in the Firebase '
          'console and paste its config here if you need a desktop build.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Registered in Firebase console → Project settings → Your apps → Web
  /// ("Optic" web app), project optic-8f64e.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '*****',
    appId: '*****',
    messagingSenderId: '***',
    projectId: '*****',
    authDomain: '*****',
    storageBucket: '*****',
    measurementId: '*****',
  );

  /// Registered in Firebase console → Project settings → Your apps →
  /// Android ("Optic", package com.example.optic), project optic-8f64e.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '*****',
    appId: '****',
    messagingSenderId: '****',
    projectId: '****',
    storageBucket: '****',
  );

  /// Registered in Firebase console → Project settings → Your apps →
  /// iOS ("Optic", bundle id com.example.optic), project optic-8f64e.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***',
    appId: '***',
    messagingSenderId: '***',
    projectId: '***',
    storageBucket: '***',
    iosBundleId: '****',
  );
}
